# Common vars
#############################################
availability_zone: melbourne-qh2-uom
instance_network: qh2-uom-internal
instance_flavor_2c: uom.mse.2c9g
instance_flavor_1c: uom.mse.1c4g #uom.general.2c8g
instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb # Ubuntu 20.04
instance_key_name: Team61 # ssh private key
project_working_directory: /home/jiacheng/Desktop/CCC/Team61/COMP90024_A2

# Volume
#############################################
volumes:
  - vol_name: volu_db1
    vol_size: 90
    device: /dev/vdb
    mountpoint: /data
  - vol_name: volu_db2
    vol_size: 90
    device: /dev/vdb
    mountpoint: /data
  - vol_name: volu_db3
    vol_size: 90
    device: /dev/vdb
    mountpoint: /data
  - vol_name: volu_db4
    vol_size: 90
    device: /dev/vdb
    mountpoint: /data

# Security group
#############################################
security_groups:
  - name: Any
    description: "Any access"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0

# Instance
#############################################
instances2c:
  - name: instance1-frontend
    security_groups: ['Any']
    volumes: ['volu_db1']
  - name: instance2-backend
    security_groups: ['Any']
    volumes: ['volu_db2']
  - name: instance3-backend
    security_groups: ['Any']
    volumes: ['volu_db3']

instances1c:
  - name: instance4-analysis
    security_groups: ['Any']
    volumes: [ 'volu_db4' ]